include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-raw-types: false

linter:
  rules:
    always_use_package_imports: false
    cascade_invocations: false
    lines_longer_than_80_chars: false
    parameter_assignments: false
    public_member_api_docs: false
