name: subject
description: >-
  Observer Pattern implementation for Dart, using callbacks, streams, etc...
  Subject code generator with annotations, to automatically generate an observable interface for any class.
version: 0.0.2
repository: https://github.com/DrafaKiller/ObserverPattern-dart
issue_tracker: https://github.com/DrafaKiller/ObserverPattern-dart/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  analyzer: ^5.6.0
  build: ^2.3.1
  code_builder: ^4.4.0
  source_gen: ^1.2.7

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^1.0.0
