name: observer
description: Observer Pattern implementation for Dart. Generalized for any type of data, using callbacks, streams and states.
version: 0.0.1
repository: https://github.com/DrafaKiller/Observer-dart
issue_tracker: https://github.com/DrafaKiller/Observer-dart/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  build: ^2.3.1
  analyzer: ^4.4.0
  source_gen: ^1.2.6
  code_builder: ^4.4.0

dev_dependencies:
  lints: ^1.0.0