name: subject_gen
description: >-
  Dev-dependency for subject generation. It is meant to be used as a support dependency for the subject package.
version: 1.0.1
repository: https://github.com/DrafaKiller/ObserverPattern-dart/tree/main/packages/subject_gen
issue_tracker: https://github.com/DrafaKiller/ObserverPattern-dart/issues

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  analyzer: ^5.6.0
  build: ^2.3.1
  build_runner: ^2.3.3
  code_builder: ^4.4.0
  source_gen: ^1.2.7
  
dev_dependencies:
  lints: ^2.0.0
  very_good_analysis: ^3.1.0
  